export const GET_LEGAL_HOLDS = "GET_LEGAL_HOLDS";
export const GET_ON_HOLD_DOCUMENTS = "GET_ON_HOLD_DOCUMENTS";
export const CLEAR_ON_HOLD_DOCUMENTS = "CLEAR_ON_HOLD_DOCUMENTS";
export const TOTAL_ON_HOLD_DOCS = "TOTAL_ON_HOLD_DOCS";
export const ON_HOLD_API_BODY_DATA = "ON_HOLD_API_BODY_DATA";
