export const GET_SIMPLESEARCH = "GET_SIMPLESEARCH";
export const LOADING = "LOADING";
export const ERROR = "ERROR";
export const SUCCESS = "SUCCESS";
export const GET_SIMPLESEARCHRESULT = "GET_SIMPLESEARCHRESULT";
export const GET_SAVEDSEARCH = "GET_SAVEDSEARCH";
export const QUERYBUILDER = "QUERYBUILDER";
export const CLEAR_SEARCHED_RESULTS = "CLEAR_SEARCHED_RESULTS";
export const TOTAL_SIMPLE_SEARCHED_DOCS = "TOTAL_SIMPLE_SEARCHED_DOCS";
export const MOVED_TO_FILTER = "MOVED_TO_FILTER";
export const GET_ATTACHMENTID = "GET_ATTACHMENTID";
export const EMPTY_ATTACHMENT = "EMPTY_ATTACHMENT";
export const GET_ATTACHMENT_SAVE = "GET_ATTACHMENT_SAVE";
export const SMARTSEARCHACESSTOKEN = "SMARTSEARCHACESSTOKEN";
export const GETFILTERAGGREGATIONS = "GETFILTERAGGREGATIONS";

