export const GET_SMTP="GET_SMTP"
export const GET_NOTIFICATION="GET_NOTIFICATION"
export const GET_SELECTED_NOTIFICATION="GET_SELECTED_NOTIFICATION"
export const GET_NOTIFICATION_DROPDOWN_LIST="GET_NOTIFICATION_DROPDOWN_LIST"