export const GET_USERLIST = "GET_USERLIST"
export const GET_SELECTEDUSERLIST = "GET_SELECTEDUSERLIST"
export const GET_EXTERNALUSERLIST = "GET_EXTERNALUSERLIST"
export const GET_ARCHIVEDUSERLIST = "GET_ARCHIVEDUSERLIST"
export const GET_FOLDERSYNCUSERS = "GET_FOLDERSYNCUSERS"
export const GET_FOLDERSYNCHISTORY = "GET_FOLDERSYNCHISTORY"
export const GET_STUBPOLICY = "GET_STUBPOLICY"
export const GET_STUBPOLICYSETTING = "GET_STUBPOLICYSETTING"
export const GET_RETENTIONPOLICYLIST = "GET_RETENTIONPOLICYLIST"
export const GET_RETENTIONPOLICYSETTINGLIST = "GET_RETENTIONPOLICYSETTINGLIST"
export const GET_DEFAULTRETENTION = "GET_DEFAULTRETENTION"
export const GET_RETENTIONPOLICYBYID = "GET_RETENTIONPOLICYBYID"
export const GET_DELETEDDOCUMENTPOLICY = "GET_DELETEDDOCUMENTPOLICY"
export const GET_DELETEDDOCUMENTPOLICYRUNNINGSTATUS = "GET_DELETEDDOCUMENTPOLICYRUNNINGSTATUS";
export const ADD_EXTERNALUSER = "ADD_EXTERNALUSER";
export const GET_DELETEDDOCUMENTDATA = "GET_DELETEDDOCUMENTDATA";
export const DELETE_EXTERNALUSER = "DELETE_EXTERNALUSER";
export const GET_ARCHIVALUSERTYPE = "GET_ARCHIVALUSERTYPE"

export const GET_GLOBAL_AUTO_LABELING = "GET_GLOBAL_AUTO_LABELING";
export const GET_LEGAL_HOLD_AUTO_LABELING = "GET_LEGAL_HOLD_AUTO_LABELING";
export const GET_SORTED_GLOBAL_LABEL = "GET_SORTED_GLOBAL_LABEL";

