export const GET_FOLDER_STRUCTURE = "GET_FOLDER_STRUCTURE";
export const GET_ALL_MAILBOXES = "GET_ALL_MAILBOXES";
export const GET_FOLDER_RELATED_DOCUMENTS = "GET_FOLDER_RELATED_DOCUMENTS";
export const TOTAL_FOLDER_DOCS = "TOTAL_FOLDER_DOCS";