export const GET_APPLICATIONPARAMETERS = "GET_APPLICATIONPARAMETERS";
export const GET_ACTIVEDIRECTORYLIST = "GET_ACTIVEDIRECTORYLIST";
export const GET_OULIST = "GET_OULIST";
export const ERROR="ERROR";
export const GET_GENERAL="GET_GENERAL"
export const GET_DEPLOYMENT="GET_DEPLOYMENT"
export const GET_DEPLOYMENT_SITES="GET_DEPLOYMENT_SITES"
export const GET_OULISTBYID="GET_OULISTBYID"


